Now use sync.WaitGroup for newrelic and datadog log writers.
cultureamp/glamplify pull request #16
Opened 2020-09-23 02:02 UTC by techmanmike

2020-09-23 02:20 UTC, jamestelfer commented on datadog/writer.go
> +		Timeout:   time.Second * time.Duration(helper.GetEnvInt("DATA_DOG_TIMEOUT", 5)),
Should the naming scheme of these environment variables align?

2020-09-23 02:25 UTC, matthewtapper approved these changes
lgtm

2020-09-23 02:50 UTC, techmanmike commented on datadog/writer.go
> +		Timeout:   time.Second * time.Duration(helper.GetEnvInt("DATA_DOG_TIMEOUT", 5)),
Yes - probably. What do you think. DD_LOG_ENDPOINT?

2020-09-23 02:50 UTC, jamestelfer requested changes
I've left some thoughts on the API design, and some thoughts on sending messages on demand in parallel. Interested in what you think.

2020-09-23 02:50 UTC, jamestelfer commented on datadog/writer.go
> +		Omitempty: helper.GetEnvBool(log.OmitEmpty, false),
```suggestion
		OmitEmpty: helper.GetEnvBool(log.OmitEmpty, false),
```
I suggest Pascal case to align with Go's norms

2020-09-23 02:50 UTC, jamestelfer commented on datadog/writer.go
> +}
A few thoughts on the API design here.

There are a couple of options:

1. Keep the `WaitGroup` entirely within the writer, exposing a `WaitAll()` method at the end. Then you if you don't care about losing messages, you don't call `WaitAll()`.
1. Optionally specify the `WaitGroup` to the config, but in that case don't have a `WaitAll()` method: the caller has the `WaitGroup` and can call it themselves. A possible use case here is where the user might want to share the group, or have a number of groups that it ends up waiting for.
1. As it is now, where the group is passed in, but the caller still calls `WaitAll()`.

I'd probably tend towards either (1) or (2) as being a clearer API over (3). Either way, if you go with (3) and the user hasn't specified a `WaitGroup`, I wouldn't bother with the `Sleep`, I'd document that you may lose messages unless you supply a `WaitGroup`.

2020-09-23 02:50 UTC, jamestelfer commented on datadog/writer_test.go
> +func Test_DataDog_Writer(t *testing.T) {
This test has no assertions: it's not really testing anything, especially considering the write occurs in a goroutine and any error it writes would be lost. It should probably mock out the HTTP calls such that you can assert what it should do.

2020-09-23 02:50 UTC, jamestelfer commented on datadog/writer.go
> +func post(writer *DDFieldWriter, jsonStr string) error {
If you consider this working in a high volume service, the way logs are sent here will cause issues with the number of HTTP calls that will be spawned in parallel. There's an opportunity here to push logs to a channel, and write them to datadog in batches.

This behaviour would make a good case for a `WaitAll` too.

2020-09-23 02:50 UTC, jamestelfer commented on datadog/writer.go
> +		time.Sleep(writer.Timeout)
As mentioned in another comment, IMO if a user wants to do this it should be explicit in their code, not in a dependency.

2020-09-23 02:52 UTC, techmanmike commented on datadog/writer.go
> +func post(writer *DDFieldWriter, jsonStr string) error {
I think spawning them all in parallel will be ok - somewhere internally inside GO (or OS?) it should handle writing all these 1 and a time to the network. Why add extra complexity of managing a queue or channel (which is like a queue)?

2020-09-23 02:53 UTC, techmanmike commented on datadog/writer.go
> +		time.Sleep(writer.Timeout)
So if you call WaitAll() without setting the waitgroup - then it should do nothing and just return?

2020-09-23 02:53 UTC, techmanmike commented on datadog/writer_test.go
> +func Test_DataDog_Writer(t *testing.T) {
I'll fix that - good catch

2020-09-23 02:54 UTC, techmanmike commented on datadog/writer.go
> +}
yes - agree. I think 1) is the best choice...

2020-09-23 02:55 UTC, techmanmike commented on datadog/writer.go
> +		time.Sleep(writer.Timeout)
Give 1) above, this will be removed.

2020-09-23 04:28 UTC, jamestelfer commented on datadog/writer.go
> +func post(writer *DDFieldWriter, jsonStr string) error {
I'm not up to speed with Go's limits. Two areas that do pop up in general are (a) concurrency limits and (b) TCP connection limits.

For (a), this might be OK for Go, but I'm not sure. For (2), unless the HTTP library is doing some sort of connection pooling, there is generally an OS limit in play here, in which case the logging library in use could constrain the ability of the application to make TCP connections.

You're right to keep it simple without evidence to the contrary, however this is an area that makes me ask questions. I'm just not sure what the answers are.

2020-09-23 04:34 UTC, jamestelfer commented on datadog/writer.go
> +		Timeout:   time.Second * time.Duration(helper.GetEnvInt("DATA_DOG_TIMEOUT", 5)),
That would align with the standard Datadog stuff I think

2020-09-23 04:36 UTC, jamestelfer commented on datadog/writer.go
> +func post(writer *DDFieldWriter, jsonStr string) error {
Had a quick thrash about: goroutines won't matter here, but the socket limits could (see `ulimit`). The DD API log endpoint can accept multiple messages at once too, so you'd be able to bunch them up into far fewer requests.

2020-09-23 04:38 UTC, jamestelfer commented on datadog/writer.go
> +func post(writer *DDFieldWriter, jsonStr string) error {
This could easily be a later refinement. If using this in a service, it'd be worthwhile, and it might have some benefits for a short-lived Lambda as well, in that it would reduce the number of connections made in the life of the lambda.

2020-09-24 03:26 UTC, techmanmike commented on datadog/writer.go
> +		Omitempty: helper.GetEnvBool(log.OmitEmpty, false),
opps - missed this. Fixing now...

2020-09-24 03:27 UTC, techmanmike commented on datadog/writer.go
> +func post(writer *DDFieldWriter, jsonStr string) error {
I think it is ok to kick this down the road for when it is a problem... yes?

2020-09-24 03:33 UTC, merged

2020-09-24 04:23 UTC, jamestelfer commented on datadog/writer.go
> +func post(writer *DDFieldWriter, jsonStr string) error {
Yes, but not too far. IMO it will be an issue for any service that gets appreciable volume.